site_name: Sample Components

nav:
    - Home: 'index.md'
    - Docstring: 'docstring.md'
theme:
  name: 'material'
  language: 'en'
  palette:
    scheme: default
    primary: indigo
  features:
    - header.autohide
copyright:   &copy 2022 AB

extra:
  generator: false

plugins:
  - search
  - mkdocstrings

extra_javascript:
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - def_list
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.betterem
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
