[tool.poetry]
name = "sample-components"
version = "0.1.0"
description = ""
authors = ["Aritra Biswas <40533894+pandalearnstocode@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "sample_components"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
