name: Release

on:
  push:
    branches:
      - init

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: ci.yml
        name: test_coverage_report
        path: test_coverage_report
    - name: Display structure of downloaded files
      run: ls -R
    - name: Publish Sonar Cloud Result
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Send notifications here
      run: echo "Send notifications here."
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: sonar_analysis
    steps:
    - name: Create release
      run: echo "step 1"
  notify:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Notify users
      run: echo "step 1"
